In [1]:
import numpy as np
import pandas as pd

# Task 0
Read the dataset from csv file & perform data cleaning - remove all rows, which contains `?` in some columns.
Also check for data correctness (salary & salary $K).

In [2]:
# write your code for task 0 here
df = pd.read_csv("../data/adult.csv")

df_cleaned = df[~df.apply(lambda row: row.astype(str).str.contains(r"\?").any(), axis=1)].copy()

df_cleaned["sex"].value_counts()

Male      20380
Female     9782
Name: sex, dtype: int64

# Task 1
Print the count of men and women in the dataset.

In [13]:
# write your code for task 1 here
df["sex"].value_counts()

Male      21790
Female    10771
Name: sex, dtype: int64

# Task 2
Find the average age of men in dataset

In [14]:
# write your code for task 2 here
df[df["sex"] == "Male"]["age"].mean()

39.43354749885268

# Task 3
Get the percentage of people from Poland (native-country)

In [4]:
# write your code for task 3 here
percentage_poland = (df_cleaned[df_cleaned["native-country"] == "Poland"].shape[0] / df_cleaned.shape[0]) * 100
print(percentage_poland)

0.18566408063125786

# Task 4
Get the mean and standard deviation of the age for people who earn > 50K per year. After this, get it for those who earn <= 50K.

In [18]:
# write your code for task 4 here
df[df["salary"] == ">50K"]["age"].agg(["mean", "std"]), df[df["salary"] == "<=50K"]["age"].agg(["mean", "std"])

(mean    44.249841
 std     10.519028
 Name: age, dtype: float64,
 mean    36.783738
 std     14.020088
 Name: age, dtype: float64)

# Task 5
Check, if there are some people without higher education (education: Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters, Doctorate), but with > 50K salary

In [19]:
# write your code for task 5 here
higher_edu = ["Bachelors", "Prof-school", "Assoc-acdm", "Assoc-voc", "Masters", "Doctorate"]
df[(~df["education"].isin(higher_edu)) & (df["salary"] == ">50K")]

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
7,7,52,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,45,United-States,>50K,307
10,10,37,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,80,United-States,>50K,116
27,27,54,?,Some-college,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,60,South,>50K,275
38,38,31,Private,Some-college,Married-civ-spouse,Sales,Husband,White,Male,38,?,>50K,166
55,55,43,Private,Some-college,Married-civ-spouse,Tech-support,Husband,White,Male,40,United-States,>50K,341
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32510,32510,39,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,45,?,>50K,212
32518,32518,57,Local-gov,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,>50K,116
32519,32519,46,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,48,United-States,>50K,239
32557,32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K,173
32560,32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K,243

# Task 6
Get the statistics of age for each type of education. Use `groupby` and `describe` for this.

In [20]:
# write your code for task 6 here
df.groupby("education")["age"].describe()

                count       mean        std   min    25%   50%   75%   max
education
10th            933.0  37.429796  16.720713  17.0  22.00  34.0  52.0  90.0
11th           1175.0  32.355745  15.545485  17.0  18.00  28.0  43.0  90.0
12th            433.0  32.000000  14.334625  17.0  19.00  28.0  41.0  79.0
1st-4th         168.0  46.142857  15.615625  19.0  33.00  46.0  57.0  90.0
5th-6th         333.0  42.885886  15.557285  17.0  29.00  42.0  54.0  84.0
7th-8th         646.0  48.445820  16.092350  17.0  34.25  50.0  61.0  90.0
9th             514.0  41.060311  15.946862  17.0  28.00  39.0  54.0  90.0
Assoc-acdm     1067.0  37.381443  11.095177  19.0  29.00  36.0  44.0  90.0
Assoc-voc      1382.0  38.553546  11.631300  19.0  30.00  37.0  46.0  84.0
Bachelors      5355.0  38.904949  11.912210  19.0  29.00  37.0  46.0  90.0
Doctorate       413.0  47.702179  11.784716  24.0  39.00  47.0  55.0  80.0
HS-grad       10501.0  38.974479  13.541524  17.0  28.00  37.0  48.0  90.0
Masters        1723.0  44.049913  11.068935  18.0  36.00  43.0  51.0  90.0
Preschool        51.0  42.764706  15.126914  19.0  31.00  41.0  53.5  75.0
Prof-school     576.0  44.746528  11.962477  25.0  36.00  43.0  51.0  90.0
Some-college   7291.0  35.756275  13.474051  17.0  24.00  34.0  45.0  90.0

# Task 7
Compare the married and non-married men salaries. Who earns more? (>50K or <=50K)
Married men are those, whom `marital-status` starts with "Married". Others are not.

In [3]:
# write your code for task 7 here
men = df_cleaned[df_cleaned["sex"] == "Male"].copy()
men.loc[:, "is_married"] = men["marital-status"].str.startswith("Married")

salary_comparison = men.groupby("is_married")["salary"].value_counts(normalize=True).unstack()
salary_comparison

salary         <=50K      >50K
is_married
False       0.911506  0.088494
True        0.552016  0.447984

# Task 8
Get the max hours per week some person works. How many people works the same amount of hours per week?

In [24]:
# write your code for task 8 here
max_hours = df["hours-per-week"].max()
count_max_hours = df[df["hours-per-week"] == max_hours].shape[0]

max_hours, count_max_hours

(99, 85)

# Task 9
Analyze the correlation between data in dataset. Understand connected fields in it and print highlight thier connection.

In [26]:
# write your code for task 9 here
corr_matrix = df.select_dtypes(include=["int64", "float64"]).corr()
print(corr_matrix)

strong_corr = corr_matrix[(corr_matrix.abs() > 0.5) & (corr_matrix.abs() < 1.0)].stack()
print(strong_corr)

                Unnamed: 0       age  hours-per-week  salary K$
Unnamed: 0        1.000000  0.001286        0.000607  -0.001666
age               0.001286  1.000000        0.068756   0.201774
hours-per-week    0.000607  0.068756        1.000000   0.196916
salary K$        -0.001666  0.201774        0.196916   1.000000
Series([], dtype: float64)